---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: Service1 Name
        url: http://localhost:91/service1/docs
        version: 2.0
      - 
        name: Service2 Name
        url: http://localhost:92/service2/docs
        version: 2.0

 
    